### ISSUE TITLE
Multiple state change trigger for single change in state

### ISSUE THREAD

**Issue by rkokkelk** [athombv/com.irobot.roomba980#11]
Hi,

First of all great app which functions very well! However, when a state changes for the roomba, e.g. when the roomba is stopped, there are multiple triggers fired for a single state. 

E.g. I have the following triggers defined: 
1. Roomba state changed to cleaning
2. Roomba state changed to charging

When the roomba is stopped, both trigger 1 & 2 are fired two times, so a total of four triggers. Hopefully this issue can be fixed in the following version.

Thanks again for the hard work. 

p.s. I use version 1.0.0 for homey version 1.5.3 and I use it with Roomba 696, which works great with the app.

**Comment by MatthewWaanders** [comment]
Hi @rkokkelk,

Could you let us know if this issue still persists?

**Comment by rkokkelk** [comment]
Yes, I've just checked this morning and the issue still persists. I've only added two trigger for Roomba when the 'status is changed to' start or stop. However, both flows are triggered when the Roomba has started, stopped, is charged or is at the home station. 

I'm still using application version `1.0.0`.

**Comment by rkokkelk** [comment]
I've just verified this issue for version `1.0.1`, but unfortunately the same issue still persists. 

The behaviour is still the same as in version `1.0.0`. I've got two triggers for when the state is changed to 'cleaning' or 'charging', but if the Roomba has started, stopped, or is fully charged both of my flows are being triggered simultaneously .

**Comment by WoutervdBrink** [comment]
Hi there @rkokkelk, thank you for your feedback. Could you please send us a log for the app?

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2611
