### ISSUE TITLE
Rename app to Roomba

### ISSUE THREAD

**Issue by tomhur** [athombv/com.irobot.roomba980#15]
This app works fine with my Roomba 695 and probably works with all WiFi connected Roombas. A more describing name of app the would  be just "Roomba" to not mislead users that it is only 980 that works.

Thank you for a good app.

**Comment by WoutervdBrink** [comment]
Thank you for your suggestion! I have renamed the app to "Roomba" in the beta version. The name will soon enough be the same for the stable app.
