### ISSUE TITLE
Can’t add new Roomba

### ISSUE THREAD

**Issue by Veldkornet** [athombv/com.irobot.roomba980#22]
Homey 2.0.4
Roomba App: 1.0.4

When I try to add a Roomba, it tells me that there are no new devices to add. 

I assume it’s scanning the network? My Roomba is in a different VLAN, so how can I manually enter its details?

**Comment by Veldkornet** [comment]
I see the store still haze version 1.0.4 but here on Github v2 seems to be around for a while already...
Am I using the latest version?

**Comment by Veldkornet** [comment]
Updated to app version 2.0.2, Sams issue occurs.

**Comment by carp3-noctem** [comment]
Did you try a delete and reboot of homey, then install the latest version?
This fixes the issue for me.

**Comment by Veldkornet** [comment]
No, same issue. It doesn't find anything.

**Comment by carp3-noctem** [comment]
this happens sometimes to me as well, then waken up the romba and wait a few minutes brings it back to the discovered devices. Did you allready try that a few times?

**Comment by Veldkornet** [comment]
Support advised that it's currently not possilb eto go across VLAN's. So I've jsut moved it into the same VLAN and now it works fine.
