### ISSUE TITLE
Bin full state catch - possible

### ISSUE THREAD

**Issue by carp3-noctem** [athombv/com.irobot.roomba980#23]
Hey Guys,
Is it possible that you implement the bin full message or the stuck message so we are able to use it as flowcard (when, and)?

Should be possible according to what I have read about the inofficial api.

Thanks and Kind regards

**Comment by jeroenvano** [comment]
Just to let you know, IFTTT supports the stuck  message so must able for Homey to also add.

**Comment by RobinBol** [comment]
Thank you for reporting your issue. Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Alternatively, use the 'Report an issue' button on the App page in the Homey Apps store to create an issue at the correct location. This issue will be closed now, our apologies for the inconvenience.
