### ISSUE TITLE
Support for Roomba S9+

### ISSUE THREAD

**Issue by gcraenen** [athombv/com.irobot.roomba980#27]
Is it possible to add support for the Roomba S9+?

**Comment by RobinBol** [comment]
Hi! Thank you for requesting support for a device.

Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Alternatively, use the 'Report an issue' button on the App page in the Homey Apps store to create an issue at the correct location.

Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
